### ISSUE TITLE
Administrator users role cant access calender

### ISSUE THREAD

**Issue by malasaad82** [openrestaurant/restaurant#11]
Hi,
I created new user and gave him Administrator role.. and checked all the permisions and he still cant access to 
admin/reservations/calendar
admin/reservations/manage

You are not authorized to access this page.

Any help
Thanks

**Comment by arshad** [comment]
Looks like there was a typo in the permission. Working on a fix.

**Comment by arshad** [comment]
Fixed. You can grab a copy a restaurant_reservation module here. https://github.com/drupalrestaurant/restaurant_reservation

Click on Download Zip. Extract and place it under profiles/restaurant/modules/restaurant/

Clear the cache.

**Comment by malasaad82** [comment]
Sorry!,  It does not work! , I tried to put it and flush the cache but still not working.. and I gave the user administrator role and administrator checked box everything..

reservations/calendar
reservations/manage

Access denied
You are not authorized to access this page.

**Comment by arshad** [comment]
We shipped a new release: http://open.restaurant. Fixed a lot of bugs. Please test and let us know. Closing this issue for now. Feel free to reopen.
